<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Shri-PC" name="testNGPractice.DemoTestXml" tests="9" failures="2" timestamp="2021-10-29T21:28:41 IST" time="4.168" errors="0">
  <testcase name="verifyLoginTitle" time="3.384" classname="testNGPractice.DemoTestXml"/>
  <system-out/>
  <testcase name="verifyLogo" time="0.108" classname="testNGPractice.DemoTestXml"/>
  <system-out/>
  <testcase name="verifyCourses" time="0.005" classname="testNGPractice.DemoTestXml">
    <skipped/>
  </testcase> <!-- verifyCourses -->
  <system-out/>
  <testcase name="verifyDashboardTitle" time="0.008" classname="testNGPractice.DemoTestXml">
    <skipped/>
  </testcase> <!-- verifyDashboardTitle -->
  <system-out/>
  <testcase name="verifyCourses" time="0.002" classname="testNGPractice.DemoTestXml">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at testNGPractice.DemoTestXml.verifyCourses(DemoTestXml.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyCourses -->
  <system-out/>
  <testcase name="verifyDashboardTitle" time="0.015" classname="testNGPractice.DemoTestXml">
    <skipped/>
  </testcase> <!-- verifyDashboardTitle -->
  <system-out/>
  <testcase name="verifyDashboardTitle" time="0.014" classname="testNGPractice.DemoTestXml">
    <failure type="java.lang.AssertionError" message="expected [JavaByKiran | Dashboard1] but found [JavaByKiran | Dashboard]">
      <![CDATA[java.lang.AssertionError: expected [JavaByKiran | Dashboard1] but found [JavaByKiran | Dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testNGPractice.DemoTestXml.verifyDashboardTitle(DemoTestXml.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- verifyDashboardTitle -->
  <system-out/>
  <testcase name="verifyValidLogin" time="0.626" classname="testNGPractice.DemoTestXml"/>
  <system-out/>
  <testcase name="verifyCourses" time="0.006" classname="testNGPractice.DemoTestXml">
    <skipped/>
  </testcase> <!-- verifyCourses -->
  <system-out/>
</testsuite> <!-- testNGPractice.DemoTestXml -->
